WS-2 Adding new location
MichalKulygin/weather-service pull request #4
Opened 2021-03-31 21:06 UTC by MichalKulygin

2021-04-01 18:53 UTC, klezner commented on src/main/java/com/mkgn/weatherservice/exceptions/EmptyInputException.java
> +}
Exception is unnecessary

2021-04-01 18:53 UTC, klezner commented on src/main/java/com/mkgn/weatherservice/exceptions/CardinalsOutOfRangeException.java
> +}
Exception is unnecessary

2021-04-01 19:45 UTC, MichalKulygin commented on src/main/java/com/mkgn/weatherservice/exceptions/EmptyInputException.java
> +}
OK, removed

2021-04-01 19:45 UTC, MichalKulygin commented on src/main/java/com/mkgn/weatherservice/exceptions/CardinalsOutOfRangeException.java
> +}
OK, removed

2021-04-01 19:56 UTC, klezner commented on src/test/java/com/mkgn/weatherservice/location/LocationServiceTest.java
> +        assertThat(locationArgumentCaptor.getValue().getCity().equals("City"));
create a variable for locationArgumentCaptor.getValue()

2021-04-01 19:59 UTC, MichalKulygin commented on src/test/java/com/mkgn/weatherservice/location/LocationServiceTest.java
> +        assertThat(locationArgumentCaptor.getValue().getCity().equals("City"));
done

2021-04-01 20:11 UTC, klezner approved these changes

2021-04-01 20:44 UTC, klezner approved these changes

2021-04-03 12:44 UTC, MisQl commented on src/main/java/com/mkgn/weatherservice/location/LocationController.java
> +        return ResponseEntity.status(201).body(responseBody);
201 -> HttpStatus.CREATED

2021-04-03 12:44 UTC, MisQl commented on src/main/java/com/mkgn/weatherservice/location/LocationService.java
> +
unnecessary new line

2021-04-03 12:44 UTC, MisQl commented on src/main/java/com/mkgn/weatherservice/location/LocationService.java
> +        location.setRegion(region);
it saves trash values like "   "

2021-04-03 12:44 UTC, MisQl commented on src/test/java/com/mkgn/weatherservice/location/LocationServiceTest.java
> +
unnecessary new line

2021-04-03 12:44 UTC, MisQl commented on src/test/java/com/mkgn/weatherservice/location/LocationServiceTest.java
> +        assertThat(location.getRegion().equals(""));
it should be a null value

2021-04-05 20:26 UTC, MichalKulygin commented on src/main/java/com/mkgn/weatherservice/location/LocationController.java
> +        return ResponseEntity.status(201).body(responseBody);
OK

2021-04-05 20:33 UTC, MichalKulygin commented on src/test/java/com/mkgn/weatherservice/location/LocationServiceTest.java
> +        assertThat(location.getRegion().equals(""));
Renamed test method to createLocation_whenRegionIsEmpty_thenCreatesNewLocation()

2021-04-05 20:51 UTC, klezner approved these changes

2021-04-08 20:00 UTC, MisQl commented on src/test/java/com/mkgn/weatherservice/location/LocationServiceTest.java
> +        assertThat(location.getRegion().equals(""));
it should be a null value

2021-04-09 09:16 UTC, klezner requested changes

2021-04-09 09:16 UTC, klezner commented on src/test/java/com/mkgn/weatherservice/location/LocationServiceTest.java
> +        assertThat(location.getRegion().equals(""));
location.getRegion() == null

2021-04-09 09:17 UTC, klezner commented on src/test/java/com/mkgn/weatherservice/location/LocationServiceTest.java
> +        assertThat(location.getRegion().equals(""));
location.getRegion() == null

2021-04-11 13:28 UTC, MichalKulygin commented on src/test/java/com/mkgn/weatherservice/location/LocationServiceTest.java
> +        assertThat(location.getRegion().equals(""));
fixed

2021-04-11 18:43 UTC, MisQl commented on src/test/java/com/mkgn/weatherservice/location/LocationServiceTest.java
> +        assertThat(location.getRegion() == null);
assertThat(location.getRegion()).isNull();

2021-04-14 16:04 UTC, MichalKulygin commented on src/test/java/com/mkgn/weatherservice/location/LocationServiceTest.java
> +        assertThat(location.getRegion() == null);
fixed

2021-04-25 15:09 UTC, MisQl commented
is OK

2021-04-25 15:09 UTC, MisQl approved these changes

2021-04-25 15:27 UTC, merged